In [ ]:
import numpy as np


In [ ]:
a=['hamna','henna','nihal']

In [ ]:
for i in a:
  print (i)

hamna
henna
nihal


In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [ ]:
np.random.rand(5)

array([0.23411063, 0.56677201, 0.25440456, 0.37186757, 0.43011438])

In [ ]:
np.random.randn(5)

array([ 2.10304459, -0.89360112,  1.66431791, -0.16126412, -0.18806874])

In [ ]:
np.random.randn(5,5)

array([[-0.08450207,  0.91302547,  1.27300043, -0.19660662, -0.09229755],
       [-0.58690469, -0.45394231, -1.01336124,  0.26869826,  0.75024095],
       [ 0.9676769 ,  0.25227586,  1.01997235,  1.18296743, -2.97925   ],
       [ 1.30583329,  1.11044373,  1.60929121, -0.81361167, -0.56306333],
       [ 0.5921825 ,  0.2396589 ,  1.1080343 , -0.94604681,  0.89064021]])

In [ ]:
np.random.randint

<function RandomState.randint>

In [ ]:
np.random.randint(1,100)

58

In [ ]:
new=np.random.randint(1,100,10)

In [ ]:
new

array([95, 33, 11, 26, 56, 50, 53, 60, 61, 20])

In [ ]:
new.shape

(10,)

In [ ]:
new.reshape(5,2)

array([[95, 33],
       [11, 26],
       [56, 50],
       [53, 60],
       [61, 20]])

In [ ]:
new.shape

(10,)

In [ ]:
new.max()

95

In [ ]:
new.argmax()

0

In [ ]:
array=np.arange(0,10)

In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
array=([[32,30,31],[40,41,42],[34,56,78]])

In [ ]:
array

[[32, 30, 31], [40, 41, 42], [34, 56, 78]]

In [ ]:
arr=np.array([[32,30,31],[40,41,42],[34,56,78]])

In [ ]:
arr

array([[32, 30, 31],
       [40, 41, 42],
       [34, 56, 78]])

In [ ]:
arr[1,1]

41

In [ ]:
arr[:2,:2]

array([[32, 30],
       [40, 41]])

In [ ]:
arr[1:,2:]

array([[42],
       [78]])

In [ ]:
arr[1:,:2]

array([[40, 41],
       [34, 56]])